version: "3.8"

services:
  comic:
    container_name: comic-rest-api
    image: comic-rest-api
    restart: on-failure
    ports: 
      - "3000:3000"
    depends_on: 
      - mysql
    networks:
      - comic-networks
    environment: 
      - PORT=3000
      - HOST=mysql
      - USER=root
      - PASSWORD=password
      - DATABASE=rest 
  mysql:
    container_name: mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=rest
    volumes:
      - ./database/dump.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - comic-networks  
networks:
  comic-networks:
    name: comic-networks 
